version: "3"

#TheHive & Cortex
services:
  elasticsearch:
    container_name: elasticdb
    image: elasticsearch:7.13.2
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    mem_limit: 1024m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes: 
      - ${ELASTIC_DATA}:/var
  cortex:
    container_name: cortex
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    mem_limit: 1024m
    command: --no-config
    volumes:
      -  ${CORTEX_CONFIG}/:/etc/cortex/
  thehive:
    container_name: thehive
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    mem_limit: 1024m
    command: --no-config
    volumes:
      - ${THEHIVE_CONFIG}/:/etc/thehive/
#MISP
  db:
    container_name: misp_db
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}:/var/lib/mysql
    mem_limit: 512m
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  web:
    build: misp/build
    depends_on:
      - db
    container_name: misp_web
    image: misp:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /dev/urandom:/dev/random
      - ${WEB_DIR}:/var/www/MISP
    mem_limit: 512m
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=${MISP_BASEURL}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}

  viper:
    build: viper
    ports:
      - "0.0.0.0:8080:8080"
    mem_limit: 512m
  