version: "3.8"

#TheHive & Cortex
services:
  elasticsearch:
    image: 'grievergf/elasticsearch4cortex'
    container_name: elasticsearch
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2048m
  cortex:
    image: 'thehiveproject/cortex:latest'
    container_name: cortex
    restart: unless-stopped
    command:
      --job-directory ${JOB_DIRECTORY}
    environment:
      - 'JOB_DIRECTORY=${JOB_DIRECTORY}'
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - ${JOB_DIRECTORY}:${JOB_DIRECTORY}
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'
    mem_limit: 1024m  
  thehive:
    image: 'thehiveproject/thehive4:latest'
    container_name: 'thehive4'
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - '0.0.0.0:9000:9000'
    links: 
      - elasticsearch
      - cortex  
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./vol/thehive/db:/opt/thp/thehive/db
      - ./vol/thehive/data:/opt/thp/thehive/data
      - ./vol/thehive/index:/opt/thp/thehive/index
    command: '--no-config --no-config-secret'
    mem_limit: 1024m
#MISP
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    mem_limit: 512m
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
      - "MYSQL_ROOT_HOST=172.*.*.*"
    mem_limit: 512m
    volumes:
      - "./vol/mysql:/var/lib/mysql"
  misp:
    image: coolacid/misp-docker:core-latest
    container_name: misp
    restart: unless-stopped
    depends_on:
      - redis
      - db
    ports:
      - "80:80"
      - "443:443"
    environment:
      - 'HOSTNAME=$MISP_URL_BASE'
      - "REDIS_FQDN=redis"
      - "INIT=true"             # Initialze MISP, things includes, attempting to import SQL and the Files DIR
      - "CRON_USER_ID=1"        # The MISP user ID to run cron jobs as
      - "DISIPV6=true" # Disable IPV6 in nginx
    mem_limit: 512m
    links:
      - db
  misp-modules:
    image: coolacid/misp-docker:modules-latest
    container_name: misp-modules
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db
    mem_limit: 512m
## Viper
  viper:
    image: grievergf/viper
    container_name: viper
    ports:
      - "0.0.0.0:8080:8080"
    mem_limit: 512m

