repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args:
        - --max-line-length=160
    -   id: check-merge-conflict
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
