language: python

cache: pip

python:
    - "3.6"

sudo: required

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq jq moreutils
    - pip install jsonschema

script:
    - ./validate_all.sh
